/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "gpio.h"
#include "uart.h"
#include <stdio.h>
#include "spi.h"
#include "imu.h"
bool button_state;

int16_t accel_x, accel_y, accel_z;
double accel_x_g, accel_y_g, accel_z_g;
uint8_t data_buffer[6];
uint8_t * add;
#define who_am_i (0x0F)
int main(void)
{
	/*Initialize LED*/
	led_init();
	uart_init();
	button_init();

	imu_init();
	    while (1)
	    {
	         //Read accelerometer data starting from the data start
	         //register

	        imu_read(ICM20948_REG_DATA_START, data_buffer);

	        //Combine high and low bytes to form the accelerometer data
	        accel_x = (int16_t)((data_buffer[0] << 8) | data_buffer[1]);
	        accel_y = (int16_t)((data_buffer[2] << 8) | data_buffer[3]);
	        accel_z = (int16_t)((data_buffer[4] << 8) | data_buffer[5]);
	        // Convert raw data to g values
	        accel_x_g = accel_x * 0.0078;
	        accel_y_g = accel_y * 0.0078;
	        accel_z_g = accel_z * 0.0078;
	        //Print values for debugging purposes
	    	imu_read(who_am_i, add);

	        //printf("accel_x : %d accel_y : %d  accel_z : %d\n",accel_x,accel_y,accel_z);

	    	printf("IICM20948 : 0x%02X\n", who_am_i);
	    }
	    return 0;

}
